# Generated by Django 5.0 on 2023-12-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_company_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='qr_logo',
            field=models.ImageField(default='sda', upload_to='qr_logos/'),
            preserve_default=False,
        ),
    ]
